### ISSUE TITLE
jsonapi.org 1.0 compability?

### ISSUE THREAD

**Issue by Suven** [FriendsOfCake/crud#310]
Hey all,

What do you think about jsonapi.org-compability?

I like the fact that it is at least some 'common' standard which different backend- and frontend-applications may implement. One could argue about how pragmatic or feasible that particular standard is when you are only building your 'own' API.

I definitely would like to work on smth cake-ready that implements it (maybe via https://github.com/tobscure/json-api ). The question is wether or not you are interested in seeing it in CRUD or if I am creating a plugin from scratch.

**Comment by ADmad** [comment]
> ...if I am creating a plugin from scratch.

You don't need to start from scratch. Just create a plugin which contains listeners which can be used instead of Crud's ApiListener and ApiPaginationListener.

**Comment by jippi** [comment]
@Suven by all means, submit it as a listener for CRUD ! :)

**Comment by jadb** [comment]
I think the having the option to switch between preferred "standards" would be neat. Go for it @Suven!

**Comment by michelpeters** [comment]
So, do I understand it correctly when saying that this will also include support for URL's like used on the referenced jsonapi.org website: `http://example.com/posts/1/comments`? Because, this is not how the normal Cake URL conventions work. I know you can write your own router code, but I guess it gets complex pretty quickly (and irritating to add all the urls in all different incarnations ).

I've read the spec on jsonapi.org quickly, so I might have missed it, but I'm not sure the URL format is part of the spec. If it is, I'm certainly interested in this project as well. If it's not, ofcourse I still applaud more specs/formats to be supported.

**Comment by jadb** [comment]
Cake works this way already, it's just not advised to nest a lot of resources. One level is not so bad though.

[reference](http://book.cakephp.org/3.0/en/development/routing.html#creating-nested-resource-routes)

**Comment by jippi** [comment]
I'm fine with both - don't see the hard requirement to nest the resources, can be flat by default and then nested by simply changing your routes later per app

**Comment by ADmad** [comment]
Closing as no one has shown interest in implementing this. Those looking to generate responses following jsonapi standard can check out https://github.com/josbeir/cakephp-json-api

**Comment by bravo-kernel** [comment]
Fellow friends, I have opened a PR containing a JsonApiListener, all feedback more than welcome.
