### ISSUE TITLE
Only access an users record

### ISSUE THREAD

**Issue by lennardschutter** [FriendsOfCake/crud#489]
I want to by default only access an users record when they are trying to edit, view or delete a record in any table.

Each table has a column with the users account id.

How would I achieve this?

**Comment by davidyell** [comment]
So you want to ensure that a user can only change the things which belong to them?

I'd be tempted here to use the `isAuthorized()` method and the AuthComponent, as you're talking about Authorization.

This is a method in the `AppController`, which you can use to check stuff like this. Have a look at the AuthComponent in [The Book](http://book.cakephp.org/).

**Comment by ADmad** [comment]
Your issue is primarily related to authorization and not Crud itself. However an easy way would be use the [Crud.afterFind](http://crud.readthedocs.io/en/latest/actions/edit.html#crud-afterfind) event to check check that record's `user_id` matches the logged in user's id and if don't throw an exception.
