### ISSUE TITLE
Adding an item returns the list of all items

### ISSUE THREAD

**Issue by hervethouzard** [FriendsOfCake/crud#545]
Hello,

I'm using the plugin for a Rest server.
Each time I post, let say, a JSON article, the article is added but the plugin returns a list of ALL articles and I don't get the id on the inserted element.

Is there a way to remove this list of all artiles and to get the ID on the inserted item?

Bye

**Comment by bravo-kernel** [comment]
There is, made possible since this PR https://github.com/FriendsOfCake/crud/commit/5c26315cb343c6d90e854e32a312cd9ee9c353e9.

An example which does exactly what you want can be found in [crud-json-api](https://github.com/FriendsOfCake/crud-json-api) . You need to stop propagation and then insert the record.

https://github.com/FriendsOfCake/crud-json-api/blob/master/src/Listener/JsonApiListener.php#L115

**Comment by hervethouzard** [comment]
Hello,

Thank you very much.
The documentation is not up to date, I think.

**Comment by bravo-kernel** [comment]
I agree `stopPropogation` could be added to the add action docs
